Update aws-list

diff --git a/bin/aws-list b/bin/aws-list
--- a/bin/aws-list
+++ b/bin/aws-list
@@ -1,16 +1,14 @@
 #!/bin/bash
 
-# clear
-
-# echo " List all the EC2 instances with their InstanceIDS "
-
-# aws ec2 describe-instances \
-#     --query 'Reservations[*].Instances[*].{InstanceID:InstanceId,Name:Tags[?Key==`Name`].Value | [0]}' \
-#     --output table
-
-#!/bin/bash
-
 clear
+
+AWS=$(command -v aws)
+
+if [ ! -f "${AWS}" ]; then
+    echo "ERROR: The aws binary does not exist."
+    echo "FIX: Please modify the \${AWS} variable in the program header."
+    exit 1
+fi
 
 echo " List all the running EC2 instances with their InstanceIDs, Names, and States "
 
